### PR TITLE
Add support for LineStringZM

### PR DESCRIPTION
**Pull request by versilov**

### CODE REVIEW

**Review by s3cur3 — CHANGES_REQUESTED** [review]
Hi @versilov! I don't object to shipping this, but first we'll need to add `%Geo.LineStringZM{}` to the upstream `geo` package. (I've pushed a test that demonstrates the failure.)

**Comment by versilov** [comment]
> we'll need to add `%Geo.LineStringZM{}` to the upstream `geo` package. 

Here it is: https://github.com/kanatohodets/geo/tree/btyler/line_string_zm

**Comment by s3cur3** [comment]
Oh! 🤦‍♂️ Sorry, I didn't realize the PR already existed. I'm gonna try to wrap my head around the changes in that [PR](https://github.com/felt/geo/pull/171) and see if I can't get it merged this week.

**Comment by s3cur3** [comment]
Released in [v3.6.0](https://github.com/felt/geo_postgis/releases/tag/v3.6.0) 👍

**Pull request merged**
